[program]
name = "GBA BIOS"
id = "gba_bios"
load_address = 0x00000000
size = 0x00004000
entry_pc = 0x00000000
speculative_literal_harvest = true
static_resume_all = true

[identity]
sha1 = "300c20df6731a33952ded8c436f7f186d25d3492"
